[project]
name = "deep"
version = "0.1.0"
description = "A multi-class classification utilities package for our groups image recognition tasks."
authors = [
    {name = "Group 69 - MsC in Data Science @NovaIMS 2024/2025"}
]
license = "MIT"
readme = "README.md"
requires-python = "<=3.11.11"
dependencies = [
    "numpy",
    "pandas",
    "keras",
    "tensorflow",
    "types-tensorflow",
    "matplotlib",
    "optuna",
    "scikit-learn",
    "opencv-python",
    "ipykernel",
    "focal-loss"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["deep"]